# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: hateshape

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: hateshape

description: 
author:
  name: hateshape
  email: hateshape@gmail.com 
  github: hateshape
  twitter: hateshaped
  #pinterest: 
  #linkedin: 
  bio: I hate lamp
  email_md5: 422acc4bdc4f248604160e20ae64f810 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: #https://www.gravatar.com/avatar/422acc4bdc4f248604160e20ae64f810 

BASE_PATH:

plugins:
  - jekyll-paginate

theme: jekyll-theme-midnight